name: ds
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.9.13
  - bokeh
  - cartopy
  - colorcet
  - graphviz
  - python-graphviz
  - dask
  - datashader
  - distributed
  - fastparquet
  - holoviews
  - ipython
  - jupyter
  - matplotlib
  - networkx>=2.0
  - numba
  - numpy
  - pandas>=0.24.1
  - param
  - python-snappy
  - rasterio
  - requests
  - scikit-image
  - scipy
  - shapely
  - snappy
  - statsmodels
  - streamz
  - xarray
  - ipympl
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.8 # Ensure the correct version of the CUDA toolkit
