name: myenv # Replace with your desired environment name
channels:
  - defaults
  - conda-forge # Optional: Add this for more package availability
dependencies:
  - python=3.8 # Specify your desired Python version
  - numpy=1.21.0
  - pandas=1.5.3
  - matplotlib=3.5.3
  - seaborn=0.12.2
  - scipy=1.9.3
  - scikit-learn=1.0.2
  - tensorflow=2.10.0 # GPU version
  - keras=2.10.0
  - h5py=3.8.0
  - numba=0.54.0
  - librosa=0.10.0
  - nltk=3.9.1
  - tqdm=4.66.5
  - requests=2.32.3
  - pyzmq=26.2.0
  - grpcio=1.66.2
  - absl-py=2.1.0
  - asttokens=2.4.1
  - astunparse=1.6.3
  - audioread=3.0.1
  - certifi=2024.8.30
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - click=8.1.7
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.0.7
  - cycler=0.10.0
  - debugpy=1.8.6
  - decorator=5.1.1
  - executing=2.1.0
  - flatbuffers=24.3.25
  - fonttools=4.54.1
  - gast=0.4.0 # Updated for TensorFlow compatibility
  - google-pasta=0.2.0
  - idna=3.10
  - ipykernel=6.29.5
  - ipython=8.12.2
  - jedi=0.19.1
  - joblib=1.4.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - kiwisolver=1.4.7
  - lazy_loader=0.4
  - libclang=18.1.1
  - markdown=3.7
  - markdown-it-py=3.0.0
  - MarkupSafe=2.1.3
  - mdurl=0.1.2
  - ml-dtypes=0.1.0
  - msgpack=1.1.0
  - namex=0.0.8
  - nest-asyncio=1.6.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - pyparsing=3.0.9
  - python-dateutil=2.8.2
  - pytz=2024.2
  - pywin32=307
  - regex=2024.9.11
  - rich=13.9.2
  - stack-data=0.6.3
  - tensorboard=2.10.1
  - tensorflow-intel=2.10.0
  - tensorflow-io-gcs-filesystem=0.31.0
  - termcolor=2.3.0
  - threadpoolctl=3.5.0
  - tornado=6.4.1
  - wcwidth=0.2.6
  - wrapt=1.14.1
